### ISSUE TITLE
Automatyczne logowanie nie działa.

### ISSUE THREAD

**Issue by Rozumek29** [Code-For-Green/iTrashMobile#1]
@PanSzelescik prawdopodobnie za każdym razem string z tokenem jest pusty

**Comment by PanSzelescik** [comment]
U mnie na https://github.com/Code-For-Green/iTrashMobile/commit/3a1e0f86bb71376cec3db5a876bd1adc58e5533b działa ale zaraz sprawdzę na https://github.com/Code-For-Green/iTrashMobile/commit/8c44f76505a2cb698a2adcab6b7d1c03eadee93f

**Comment by Rozumek29** [comment]
Przeniosłem całą twoją funkcję do loadinscreena, prawdopodobnie dlatego.

**Comment by PanSzelescik** [comment]
Trzeba użyć getSharedPreferences, żeby odczytać dane między kilkoma Activity
