### ISSUE TITLE
Klawiatura zasłania przycisk logowania

### ISSUE THREAD

**Issue by PanSzelescik** [Code-For-Green/iTrashMobile#3]
![image](https://user-images.githubusercontent.com/26679785/118399269-b1226580-b65c-11eb-8bff-008ce1a4ff9f.png)
Cały ten ekran mógłby iść trochę do góry by były widoczne przede wszystkim pola do wpisywania i przycisk zaloguj

**Comment by Rozumek29** [comment]
![image](https://user-images.githubusercontent.com/61324488/118400716-0d888380-b663-11eb-97be-98502d5bf1a8.png)
Naprawione. od https://github.com/Code-For-Green/iTrashMobile/commit/7c38aead52f0d93fb9d51942ef5ae1e6cc51a048 powinno być git
